### ISSUE TITLE
Upstart is being used instead of systemd in systems running both upstart and systemd (i.e. Ubuntu 15.04)

### ISSUE THREAD

**Issue by boris** [tomas/satan#1]
The following table is how `initctl`/`systemctl` is distributed on `upstart` or `systemd`:

|  | Upstart | SystemD |
| --- | --- | --- |
| initctl | ✔️ | ✖️ |
| systemctl | ✔️ | ✔️ |

According to the table above, the comparison is not correct:

``` javascript
if (sbin_init.match('upstart') || which('initctl')) {
    return 'upstart';
  } else if (sbin_init.match('systemd') || which('systemctl')) {
    return 'systemd';
  } else {
    return 'sysvinit';
  }
```

If a system is running Ubuntu 15.04, it will return `true` for `(sbin_init.match('upstart') || which('initctl')` because the second part (`which('initctl')`) will return TRUE although `/sbin/init` is not used by upstart but it is still there for backward compatibility. Thus, the system will be considered as "upstart" which is not correct as that distribution runs "systemd".

A workaround to this issue is remove the `which` sentence on both `upstart` and `systemd` comparison and leave `sbin_init.match('upstart')` to handle the definition of upstart, systemd or sysvinit.

**Comment by tomas** [comment]
Good find. So what you're proposing is that we switch to: 

``` js
  if (sbin_init.match('upstart')) {
    return 'upstart';
  } else if (sbin_init.match('systemd')) {
    return 'systemd';
  } else {
    return 'sysvinit';
  }
```

**Comment by boris** [comment]
Yes, I unpacked our .deb (prey-node-client) and made that modification. Then I packed again and the installation finished smoothly.

**Comment by tomas** [comment]
On what distro/version? I just check on my Ubuntu 14.04 that uses Upstart and /sbin/init is not a symlink. In this case sbin_init.match('upstart')) won't work. We need to check for something else.

**Comment by tomas** [comment]
Upon further investigation, I think this logic nails it:

``` js
  if (fs.existsSync('/run/systemd/system')) {
    return 'systemd';
  } else if (which('initctl')) { 
    return 'upstart';
  } else {
    return 'sysvinit';
  }
```

**Comment by boris** [comment]
Looks good. I'll try to check the code un the latest versions of Ubuntu.
Let's say 14.10 and 15.04 as it will cover both upstart (14.10) and systemd
(15.04)

**Comment by tomas** [comment]
Sure. Let me know how it goes!

**Comment by zlondrej** [comment]
I found this answer on stackexchange:
[How to find out if a system uses SysV, Upstart or Systemd initsystem](http://unix.stackexchange.com/a/196252/123989)

Detecting `systemd` by checking existence of directory `/run/systemd/system` should work (It doesn't exists on Ubuntu 14.04). However you might run into problems with `uselessd`. But since you doesn't support it anyway, then I guess it doesn't matter.

For better `upstart` detection it wouldn't be bad to check whether `initctl version` really contains `upstart`. But again, there is no support for other init systems at the moment so there is probably no need to check that for now. You might want to leave a comment in the code just in case.

Anyway, I've tested your code (https://github.com/tomas/satan/issues/1#issuecomment-122418038) and it works on both Ubuntu 15.04 and Ubuntu 14.04.

**Comment by tomas** [comment]
Good to know! Thanks for the heads up. As long as this logic covers the most recent versions of Ubuntu, Debian, Fedora and Arch/Gentoo, I think we're good.

**Comment by boris** [comment]
Ok, after unpacking the .deb installer and add the code @tomas suggested [here](https://github.com/tomas/satan/issues/1#issuecomment-122418038), I was able to run the installer without any problems on both Ubuntu 12.04 (upstart) and 15.04 (systemd).

**Comment by tomas** [comment]
Sweet. Pushing a new release to npm in 3,2,1...
